Bookstore/Components/CarSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Bookstore.Models;

namespace Bookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;

        public CartSummaryViewComponent(Basket temp)
        {
            basket = temp;
        }

        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Bookstore/Components/CategoriesViewComponent.cs
using System;
using System.Linq;
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class CategoriesViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoriesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke ()
        { 
            ViewBag.SelectedCategory = RouteData?.Values["Category"];

            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);


            return View(categories);
        }
    }
}

Bookstore/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1" style="width: 750px">

    <div class="card-header p-1">
        <h3 style="font-size: x-large"><abbr class="initialism" title="Book Title">@Model.Title</abbr></h3>

        <span class="badge bg-info" style="float:right; font-size: medium">
            Price: $@Model.Price
        </span>
    </div>

    <ul style="font-size: large">
        <li>Author: @Model.Author</li>
        <li>Publisher: @Model.Publisher</li>
        <li>ISBN: @Model.Isbn</li>
        <li>Category: @Model.Category</li>
        <li>Classification: @Model.Classification</li>
        <li>Page Count: @Model.PageCount</li>
    </ul>

    <form method="post" asp-page="/Purchase">

        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathandQuery()" />

        <span class="card-text">
            <button type="submit" class="btn btn-sm float-end">
                <img src="https://www.tipsandtricks-hq.com/ecommerce/wp-content/uploads/2012/05/addtocart-green-with-cart-icon.png" />
            </button>
        </span>
    </form>
</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Book Store</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>

    <div class="jumbotron" style="background-color: royalblue; color: white">
        <span class="navbar-brand" style="font-size: xx-large">
            Book Store
        </span>

        <div class="float-end">
            <vc:cart-summary></vc:cart-summary>
        </div>
    </div>

    <div class="row m-1 p-1">

        <div id="categories" class="col-3">
            <vc:categories></vc:categories>
        </div>

        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>

    <footer class="footer">
        &copy; Dan Bell
    </footer>
</body>
</html>